# Generated by Django 5.2.1 on 2025-05-15 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='newApp/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_type', models.CharField(choices=[('MG', 'Manager'), ('DR', 'Director'), ('IN', 'Investor'), ('EM', 'Employee')], max_length=2)),
            ],
        ),
    ]
